name: Issue2PR
description: 'Submits PRs to fix issues'

inputs:
  gh_token:
    description: 'your GH token'
    required: true
  openai_api_key:
    description: 'your OpenAI API key'
    required: true
  model_name:
    description: 'which OpenAI GPT model to use'
    required: true
    default: 'gpt-3.5-turbo'
  issue_number:
    description: 'id of the issue to submit a PR for'
    required: true

outputs:
  pr-number:
    description: "number of the PR opened"
    value: ${{ steps.open-pr.pr-number }}

runs:
  using: "composite"
  steps:
    - id: checkout
      uses: actions/checkout@v3

    - id: load_codebase
      run: |
        echo "codebase='
        test-issue2pr/test/function_to_fix.py
        
        ```
        def add_numbers_together(first_number: int, second_number: int):
            """
            Adds two numbers together
            """
            return first_number - second_number
        ```
        '" >> $GITHUB_OUTPUT
      shell: bash

    - id: read_issue
      run: |
        echo "issue-data=$(gh issue view ${{ inputs.issue_number }} --json=title,body,labels)" >> $GITHUB_OUTPUT
      shell: bash

    - id: make_comment
      run: |
        gh issue comment ${{ inputs.issue_number }} --body ":sparkles: Issue2PR is taking care of this issue. Hold on... :sparkles:"
      shell: bash

    - id: create_patch
      run: |
        echo '
        --- test-issue2pr/test/function_to_fix.py	2023-03-27 23:48:32.631872193 +0200
        +++ test-issue2pr/test/function_to_fix.py	2023-03-27 23:48:49.243625357 +0200
        @@ -4,4 +4,4 @@
             """
             Adds two numbers together
             """
        -    return first_number - second_number
        +    return first_number + second_number
        ' >> changes.patch
      shell: bash

    - id: setup_python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.11' 

    - id: setup_deps
      run: pip install openai
      shell: bash

    - id: get_script
      run: wget https://raw.githubusercontent.com/ZanSara/issue2pr/main/convert_issue_to_pr.py
      shell: bash

    - id: run_script
      run: |
        echo "script_output=$(python convert_issue_to_pr.py \
            ${{ inputs.openai_api_key }} \
            '${{ steps.read_issue.outputs.issue-data }}' \
            ${{ steps.load_codebase.outputs.codebase }} \ 
        )" >> $GITHUB_OUTPUT
      shell: bash

    - id: apply_patch
      run: |
        git checkout -b fix/${{ inputs.issue_number }}
        git apply --ignore-space-change --ignore-whitespace changes.patch
        rm changes.patch
      shell: bash

    - id: push_changes
      run: |
        git config user.email "bot@github.com"
        git config user.name "GitHub Action"
        git add .
        git commit -m 'fix issue ${{ inputs.issue_number }}'
        git push -u origin fix/${{ inputs.issue_number }}
      shell: bash

    - id: open_pr
      run: |
        title=$(echo '${{ steps.read_issue.outputs.issue-data }}' | jq -r ".title")
        gh pr create \
          --title "fix: $title (#${{ inputs.issue_number }})" \
          --body "Fixes #${{ inputs.issue_number }}<hr>${{ steps.run_script.outputs.script_output }}<hr> _Created by [Issue2PR](https://github.com/ZanSara/issue2pr) with some AI magic :magic_wand: Please review carefully._"
      shell: bash
