name: Issue2PR
description: 'Submits PRs to fix issues'

inputs:
  gh_token:
    description: 'your GH token'
    requited: true
  issue_number:
    description: 'id of the issue to submit a PR for'
    required: true

outputs:
  pr-number:
    description: "number of the PR opened"
    value: ${{ steps.open-pr.pr-number }}

runs:
  using: "composite"
  steps:
    - id: checkout
      uses: actions/checkout@v3

    - id: read_issue
      run: |
        echo "issue-data=$(gh issue view ${{ inputs.issue_number }} --json=title,body,labels)" >> $GITHUB_OUTPUT
      shell: bash

    - id: make_comment
      run: |
        gh issue comment ${{ inputs.issue_number }} --body ":sparkles: Issue2PR is taking care of this! :sparkles:"
      shell: bash

    - id: create_patch
      run: |
        echo '
        --- test-issue2pr/test/function_to_fix.py	2023-03-27 23:48:32.631872193 +0200
        +++ test-issue2pr/test/function_to_fix.py	2023-03-27 23:48:49.243625357 +0200
        @@ -4,4 +4,4 @@
             """
             Adds two numbers together
             """
        -    return first_number - second_number
        +    return first_number + second_number
        ' >> changes.patch
      shell: bash

    - id: apply_patch
      run: |
        git checkout -b fix/${{ inputs.issue_number }}
        git apply --ignore-space-change --ignore-whitespace changes.patch
        rm changes.patch
      shell: bash

    - id: push_changes
      run: |
        git config user.email "bot@github.com"
        git config user.name "GitHub Action"
        git add .
        git commit -m 'fix issue ${{ inputs.issue_number }}'
        git push -u origin fix/${{ inputs.issue_number }}
      shell: bash

    - id: open_pr
      run: |
        title=$(echo '${{ steps.read_issue.outputs.issue-data }}' | jq -r ".title")
        gh pr create \
          --title "fix: $title (#${{ inputs.issue_number }})" \
          --body "Fixes #${{ inputs.issue_number }}<br>Created by [Issue2PR](https://github.com/ZanSara/issue2pr). Please review carefully."
      shell: bash
