name: Issue2PR
description: 'Submits PRs to fix issues'

inputs:
  gh_token:
    description: 'your GH token'
    requited: true
  issue_number:
    description: 'id of the issue to submit a PR for'
    required: true

outputs:
  pr-number:
    description: "number of the PR opened"
    value: ${{ steps.open-pr.pr-number }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - id: read_issue
      run: echo "issue-content=$(gh issue view ${{ inputs.issue_number }})" >> $GITHUB_OUTPUT
      shell: bash

    - run: gh issue comment ${{ inputs.issue_number }} --body "Here is the issue so far:<br> ${{ steps.read_issue.outputs.issue-content }}"
      shell: bash