name: Issue2PR
description: 'Submits PRs to fix issues'

inputs:
  issue_id:
    description: 'id of the issue to submit a PR for'
    required: true

outputs:
  pr-number:
    description: "number of the PR opened"
    value: ${{ steps.open-pr.pr-number }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - run: gh issue comment ${{ inputs.issue_id }} "Hello!"