name: Issue2PR
description: 'Submits PRs to fix issues'

inputs:
  gh_token:
    description: 'your GH token'
    requited: true
  issue_number:
    description: 'id of the issue to submit a PR for'
    required: true

outputs:
  pr-number:
    description: "number of the PR opened"
    value: ${{ steps.open-pr.pr-number }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - id: read_issue
      run: |
        echo "issue-data=$(gh issue view ${{ inputs.issue_number }} --json=title,body,labels)" >> $GITHUB_OUTPUT
      shell: bash

    - run: |
        raw=${{ steps.read_issue.outputs.issue-data }}
        all=$(echo '${{ steps.read_issue.outputs.issue-data }}' | jq -r ".")
        title=$(echo '${{ steps.read_issue.outputs.issue-data }}' | jq -r ".title")
        body=$(echo '${{ steps.read_issue.outputs.issue-data }}' | jq -r ".body")
        labels=$(echo '${{ steps.read_issue.outputs.issue-data }}' | jq -r ".labels")
        gh issue comment ${{ inputs.issue_number }} --body "$raw <br> $all <br> Here is the issue so far:<br> #$title<br> $body <hr> **Labels**: $labels <hr>"
      shell: bash